# Generated by Django 3.0.8 on 2020-08-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('author', models.CharField(max_length=15, verbose_name='글쓴이')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성날짜')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('dislikes', models.IntegerField(default=0, verbose_name='싫어요')),
                ('contents', models.TextField(verbose_name='글내용')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='댓글내용')),
                ('author', models.CharField(max_length=15, verbose_name='글쓴이')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.Post')),
            ],
        ),
    ]
