# Generated by Django 3.0.8 on 2020-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0002_auto_20200804_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.TextField(null=True, verbose_name='댓글내용'),
        ),
    ]
