# Generated by Django 3.0.8 on 2020-08-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0003_auto_20200804_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=15, verbose_name='글쓴이'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.TextField(verbose_name='댓글내용'),
        ),
    ]
